# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-15 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qna',
            options={'ordering': ('id',), 'verbose_name': '질문', 'verbose_name_plural': '질문 모음'},
        ),
        migrations.AlterField(
            model_name='qna',
            name='title',
            field=models.CharField(max_length=50, verbose_name='질문'),
        ),
    ]
