# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-08 06:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import review.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='상품 이름')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='상품 설명')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='상품 제목')),
                ('image', review.fields.ThumbnailImageField(upload_to='product/%Y/%m')),
                ('description', models.TextField(blank=True, verbose_name='상품 설명')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='등록 일시')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.Product')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
