# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-15 10:52
from __future__ import unicode_literals

from django.db import migrations
import review.fields


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20181210_0149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['upload_date']},
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=review.fields.ThumbnailImageField(upload_to='review/%Y/%m'),
        ),
    ]
