# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-15 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_photo_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['-name']},
        ),
        migrations.AlterField(
            model_name='photo',
            name='price',
            field=models.CharField(max_length=50, verbose_name='상품 가격'),
        ),
    ]
