# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-15 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_auto_20181215_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='condition',
            field=models.CharField(blank=True, max_length=50, verbose_name='상품 상태'),
        ),
    ]
